# Generated by Django 4.0.5 on 2022-07-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_shop_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='product_slug',
        ),
    ]
