# Generated by Django 4.0.5 on 2022-07-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_shop_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='product_description',
            field=models.CharField(max_length=15000),
        ),
    ]
